/* soapServer.cpp
   Generated by gSOAP 2.8.10 from adp_gsoap.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.10 2012-09-07 11:28:08 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "adp-List:tauschen"))
		return soap_serve_adp_List__tauschen(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_adp_List__tauschen(struct soap *soap)
{	struct adp_List__tauschen soap_tmp_adp_List__tauschen;
	struct adp_List__tauschenResponse soap_tmp_adp_List__tauschenResponse;
	int soap_tmp_int;
	soap_default_adp_List__tauschenResponse(soap, &soap_tmp_adp_List__tauschenResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_adp_List__tauschenResponse._param_4 = &soap_tmp_int;
	soap_default_adp_List__tauschen(soap, &soap_tmp_adp_List__tauschen);
	soap->encodingStyle = NULL;
	if (!soap_get_adp_List__tauschen(soap, &soap_tmp_adp_List__tauschen, "adp-List:tauschen", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = adp_List__tauschen(soap, soap_tmp_adp_List__tauschen._param_1, soap_tmp_adp_List__tauschen._param_2, soap_tmp_adp_List__tauschen._param_3, soap_tmp_adp_List__tauschenResponse._param_4);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_adp_List__tauschenResponse(soap, &soap_tmp_adp_List__tauschenResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_adp_List__tauschenResponse(soap, &soap_tmp_adp_List__tauschenResponse, "adp-List:tauschenResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_adp_List__tauschenResponse(soap, &soap_tmp_adp_List__tauschenResponse, "adp-List:tauschenResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
